version: '3'

services:

  db:
    container_name: usersdb
    image: mongo
    hostname: db
    ports:
      - 27017:27017
    networks:
      - usersnet

  usersapi:
    container_name: usersapi
    image: fiodarsiniauski/usersapi:v1
    hostname: usersapi
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      ENVIRONMENT: development
    networks:
      - usersnet
    volumes:
      - .:/go/src/github.com/Fedkasin/users-api/
    ports:
      - 8080:8080
    depends_on:
      - db
    labels:
      kompose.service.type: loadbalancer

networks:
  usersnet:
    driver: bridge